baseURL = 'https://ccunn.ing/'
locale = 'en-us'
title = 'Caleb Cunningham'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
colorScheme = "ocean"

[params.header]
layout = "basic"
showTitle = false

[params.homepage]
layout = "profile"

[params.footer]
showAppearanceSwitcher = true