baseURL = 'https://ccunn.ing/'
locale = 'en-us'
title = 'ccunn.ing'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
colorScheme = "ocean"
defaultAppearance = "dark"

[params.header]
layout = "basic"
showTitle = true

[params.homepage]
layout = "profile"


[params.footer]
showAppearanceSwitcher = true

[params.author]
image = "images/Profile.png"
name = "Caleb Cunningham"
  links = [
    { lemmy = "https://lemmy.world/u/ccunning" },
    { mastodon = "https://mastodon.world/@ccunning" },
    { pixelfed = "https://pixelfed.social/ccunning" },
  ]